### ISSUE TITLE
a tale of 3 dickens

### ISSUE THREAD

**Issue by silky** [silky/ideas#336]
combine:

1. a christmas carol
2. a tale of two cities
3. great expectations

in order page-by-page.

@sordina

**Comment by silky** [comment]
https://github.com/silky/a-tale-of-three-dickens

**Comment by silky** [comment]
kindle rejected our book. it's okay, authors get rejected all the time, it's part of the process.

**Comment by gacafe** [comment]
I think this idea would be more interesting if you could read all books in
a series at once. For example, I am quite excited to read " The Wheel of
Time", and there are 14 books, so if I could read them in the style of "A
Tale of 3 Dickens" by Dickens, Lyndon and Noon that would be a huge hit!

**Comment by silky** [comment]
@gacafe this is an excellent idea; if you can get me the text of those books we can do it!

**Comment by sordina** [comment]
@gacafe I think it's doable for "personal commissions", but we used dickens since he is public domain now. Still if Amazon is rejecting our books anyway...
