### ISSUE TITLE
Image generator - Item, object ...

### ISSUE THREAD

**Issue by fhk** [silky/ideas#565]
It would be cool to have a tool that lets you generate or search images based on natural language and return you an image.

You provide a description and the software gives you back an image.

e.g.
Obama riding an alligator
Rabbit wearing a hat

**Comment by silky** [comment]
https://github.com/google/sg2im @fhk

**Comment by fhk** [comment]
Nice @silky

**Comment by fhk** [comment]
https://openai.com/blog/dall-e/

Looks to be solved!

**Comment by silky** [comment]
wow!
