### ISSUE TITLE
on-hold-detecting bot

### ISSUE THREAD

**Issue by silky** [silky/ideas#581]
makes a call and just gets you to a person

it knows when it's on hold and notifies you when the call is ready

@gacafe

**Comment by martiningram** [comment]
Good thinking! Did you see this?

https://support.google.com/assistant/answer/10071878?hl=en#:~:text=When%20you%20call%20a%20toll,ready%20to%20speak%20with%20you.&text=Learn%20how%20Hold%20for%20Me%20keeps%20your%20audio%20data%20secure.

**Comment by silky** [comment]
hahaha wow i had not seen that! i think this resolve this one; nice find @martiningram
