### ISSUE TITLE
literal binary sort

### ISSUE THREAD

**Issue by silky** [silky/ideas#619]
takes your input and sorts it by it's binary values literally, and reinterprets it

```
literalBinarySort [1, 2, 3]
 = literalBinarySort [b01, b10, b11]
 = asLiteral $ sort [0, 1, 1, 0, 1, 1]
 = asLiteral $ [0,0,1,1,1,1]
 = 15
```

**Comment by utdemir** [comment]
Yesterday my brain randomly decided to leave everything and think about this. Thanks.

I don't know how it is useful, but I figured it can be done without sorting, because pretty much we're counting the number of `1`'s on the binary representation:

```
> m +Data.Bits
> let literalBinarySort = subtract 1 . (2 ^) . sum . map popCount
```

(I don't know how it works on negative numbers)

**Comment by silky** [comment]
@utdemir Interestingly, I noticed that if we run `literalBinarySort` on expressions like `[1..n]` for `n > 0` then we get a cool sequence:

```
φ> ns = map (\i -> [1..i]) [1..10]
φ> map literalBinarySort ns
[1,3,15,31,127,511,4095,8191,32767,131071]
```

That is in near enough to `abs(` https://oeis.org/A094384  `)  - 1` 

The sequence itself _isn't_ in the OEIS!

**Comment by silky** [comment]
in any case i think you've solved this one @utdemir ; nice! :D
